//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Klase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JedinicaMjere
    {
        public int SifJM { get; set; }
        public string Naziv { get; set; }
    }
}
